### ISSUE TITLE
where is the data file xxx.pickle comes from?

### ISSUE THREAD

**Issue by HX-idiot** [lykaust15/SupportNet#2]

**Comment by liyu95** [comment]
Hi, thank you for your interest in our project!
The pickle file was constructed based on the sequences: http://www.cbrc.kaust.edu.sa/DEEPre/dataset.html
Basically, it incorporates the database information using BLAST and HMMER. For more information, please refer to our previous paper: https://academic.oup.com/bioinformatics/article/34/5/760/4562505.

**Comment by HX-idiot** [comment]
Thanks for your reply。BTW,
can you provide these pickle files? I dont know how to generate pickle files.
Thanks a lot!

**Comment by liyu95** [comment]
Could you please give me your email? 
Since this SupportNet paper has not been officially published, we can not completely release the data. But we can send you the data by email based on your request.
