### ISSUE TITLE
About the Memory storage problem

### ISSUE THREAD

**Issue by Arrcil** [lykaust15/SupportNet#6]
When the program is running to the end, there is a state of insufficient memory. My server's memory is 128G.  Is it not enough for this program?

**Comment by liyu95** [comment]
Sorry for the inconvenience. 
My server has 512 G so I did not check the memory problem. I would take a look at it.
Anyway, I would update the code significantly and add more datasets in these days. Hopefully, this problem would be solved automatically.

**Comment by Arrcil** [comment]
Ok, thank you very much

**Comment by liyu95** [comment]
Too much thing needs to work on. It may take some time to update the code.
For the memory issue, you can check the last function in the main script. You can see that I run and store all the data for the five classifications. You can change the code a little bit and run one classification for one program to solve the memory issue.
