### ISSUE TITLE
New  Dataset in the code

### ISSUE THREAD

**Issue by Arrcil** [lykaust15/SupportNet#7]
Can I use other data sets in the code that you provide? Do I need to modify the data format?

**Comment by liyu95** [comment]
For the other dataset, you can find the code in the submodule myIL. The code is self-explained.

**Comment by Arrcil** [comment]
Sorry, when I open submodule myIL, it appears that the page can't find.

**Comment by Arrcil** [comment]
Hello？ I can‘t open the submodule myIL’

**Comment by liyu95** [comment]
Thank you for reporting the issue. We will solve the issue ASAP.

**Comment by liyu95** [comment]
The code is now in folder 'src_image_data'.

**Comment by Arrcil** [comment]
Thank you

**Comment by Arrcil** [comment]
When I run the code of mnist_train, the following error occurred
UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node network_test/conv_1/Conv2D (defined at /home/blchen/nb/tf/SupportNet-master/src_image_data/nn_lib.py:49)  = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_network_test/Placeholder_0_1/_2427, network_test/conv_1/W/read)]]
	 [[{{node Mean_5/_2449}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3075_Mean_5", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by liyu95** [comment]
Form the information, I guess the problem is that CUDA and cuDNN library are missing.

**Comment by Arrcil** [comment]
Hello,When I run the code of mnist_train, the following error occurred
FileNotFoundError: [Errno 2] No such file or directory: 'Aug31-mnist-icarl-full2/class_ord.json'

Can you provide the json for me? Thank you.

**Comment by Arrcil** [comment]
ALGORITHM=sys.argv[1]
BASE_DIR=sys.argv[2]
if ALGORITHM=='full_data':
    CLASS_BATCH_SIZE=int(sys.argv[3])
elif ALGORITHM=="SupportNet_exemplars_set_size":
    EXEMPLARS_SET_SIZE=int(sys.argv[3])
about these parameters. can you tell me how do you design?

**Comment by Arrcil** [comment]
I have tried any version of tensorflow-gpu，but it continues to appear this problem：

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node network_test/conv_1/Conv2D (defined at /home/xujian/home/SupportNet-master/src_image_data/nn_lib.py:49)  = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_network_test/Placeholder_0_1/_2427, network_test/conv_1/W/read)]]
	 [[{{node Mean_5/_2449}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3075_Mean_5", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by guyudi** [comment]
Can i borrow the data under the data_the_feature folder for reference?

**Comment by Arrcil** [comment]
AssertionError                            Traceback (most recent call last)
<ipython-input-71-5b01267530c6> in <module>()
      6     fit(tf_tensors,tf_variables,tf_networks,fixed_params,hyper_params,data_dict,sess,resume=False,
      7             save_params=True,evaluation_metric='top1_accuracy',save_history=True,
----> 8             num_epochs=30,num_iterations=5,verbose=2,print_freq=1,pretrain_evaluation=1,override_warning=False)

~/home/SupportNet-master/src_image_data/train_procedures.py in fit(tf_tensors, tf_variables, tf_networks, fixed_params, hyper_params, data_dict_total, session, resume, save_params, evaluation_metric, save_history, num_epochs, num_iterations, verbose, print_freq, pretrain_evaluation, override_warning)
    447             if epoch==0 and pretrain_evaluation>=1:
    448                 #set test network
--> 449                 model_params=tf_networks['network_train'].get_all_model_params(session)
    450                 tf_networks['network_test'].set_model_params(model_params,session)
    451                 tf_networks['network_test'].set_prev_variables(tf_networks['network_train'].get_all_prev_variables(),session)

~/home/SupportNet-master/src_image_data/train_utils.py in test_accuracy_evaluation_plain(X_test, Y_test, test_batch_size, evaluation_tensors, session, dataset)
    103     Y_pred=np.concatenate(Y_pred)
    104     sklearn_eval_vals=sklearn_evaluation(Y_test,Y_pred)
--> 105     assert np.abs(sklearn_eval_vals['top1_accuracy']-evaluation_vals['top1_accuracy'])<1e-2
    106     evaluation_vals.update(sklearn_eval_vals)
    107     evaluation_vals['top1_accuracy']=float(evaluation_vals['top1_accuracy'])

AssertionError: 

Hello? Do you know this problem?

**Comment by Arrcil** [comment]
Hello, when I run cifar10_train, it appears the problem of kernel died. Have you ever encountered such a problem?

**Comment by liyu95** [comment]
Sorry to know you encountered those bugs.
I just tried on a new environment and set everything from scratch. I found the code worked fine for me. 
Here is the environment setup:
python: 3.5
tensorflow-gpu: 1.12.0
CUDA: 9.0.176
cudNN: 7.0

Maybe you can try MNIST or tiny ImageNet. MNIST is the easiest to run and tiny ImageNet is the newest data. 

Notice that when you run the final training block, the code will generate a JSON file. You can simply delete that file and rerun that block.

**Comment by Arrcil** [comment]
Thank you.

**Comment by Arrcil** [comment]
But don't you have this problem that when you run the cifar10_train, it will appear the kernel died?

**Comment by liyu95** [comment]
No. Cifar10 does not have too much difference from tiny ImageNet. The only difference is the data and the number of classes.

**Comment by Arrcil** [comment]
Ok, about choose the data to be train and test data. For example ,Mnist, in the code, can you tell me how to  choose the class of data,like 6,9. I want to only use two classes to train the model and test the model.

**Comment by Arrcil** [comment]
In the code， it will output four kinds of results：Plain evaluation before retrain，Plain evaluation after retrain，SVM evaluation，exemplars mean evaluation and Theoretical mean evaluation， can you tell me the  mean of second，fouth and fifth evaluation result？ and in your paper， which result do you use？
