### ISSUE TITLE
breakhis and hela10 data

### ISSUE THREAD

**Issue by Arrcil** [lykaust15/SupportNet#8]
Hello， can you upload the breakhis and hela10 dataset in the src_image_data folder?

**Comment by liyu95** [comment]
Hi, Arrcil.
Could you please check the manuscript? Most of your questions can be answered by the manuscript, including the download links of the two datasets you are asking here. Thanks.

**Comment by Arrcil** [comment]
OK， but the link  of the dataset does not exist， and when the dataset that I download，it can be used by the code.

在2018-12-14 03:05:33，徐剑17120432@bjtu.edu.cn写道：

Hi, Arrcil.
Could you please check the manuscript? Most of your questions can be answered by the manuscript, including the download links of the two datasets you are asking here. Thanks.

**Comment by Arrcil** [comment]
OK， but the link of the dataset does not exist，for example Hela10. And when  I download the dataset ，it can be used by the code.

**Comment by Arrcil** [comment]
OK， but the link of the dataset does not exist，for example Hela10. And when I download the dataset ，it can not be used by the code.

**Comment by liyu95** [comment]
http://murphylab.web.cmu.edu/data/
Choose the 2D HeLa one. This is a famous dataset.
